/* Household data stay in this browser. Energy and value estimates are separate from project cashflow. */
(function () {
 'use strict';
 const KEY='energy-optimizer.house.v1';
 const groups=[
  {title:'Dein Haus',intro:'Die bekannten Angaben sind vorausgefüllt. Prüfe insbesondere die Flächen: Wohnfläche und Gebäudenutzfläche sind verschiedene Größen.',fields:[
   ['ownArea','Selbst genutzte Wohnfläche',188,'m²',1,2000,'Deine Angabe'],['rentArea','Wohnfläche Einliegerwohnung',93,'m²',0,2000,'Deine Angabe'],['land','Grundstück',1400,'m²',1,50000,'Deine Angabe'],['year','Baujahr',2007,'Jahr',1800,2026,'Deine Angabe; Nachweis von 2006'],['an','Gebäudenutzfläche Aₙ',400.62,'m²',1,5000,'Wärmeschutznachweis, rechnerische Bezugsfläche'],['rent','Monatliche Nettokaltmiete',990,'€',0,20000,'Deine Angabe'],['occupants','Bewohner insgesamt',4,'Personen',1,30,'Je Wohnung zwei Personen']]},
  {title:'Wärme heute',intro:'Gasabrechnung 06.02.2024–05.02.2025: 26.530,69 kWh und 2.685,42 €. Holz wird auf Heizwertbasis ergänzt. Wetterbereinigung fehlt.',fields:[
   ['gas','Abgerechneter Gasverbrauch',26530.69,'kWh/Jahr',0,300000,'Gasabrechnung 2025; Brennwert'],['gasCost','Historische Gaskosten inkl. Grundpreis',2685.42,'€/Jahr',0,50000,'Gasabrechnung 2025; kein aktueller Tarif'],['wood','Gestapeltes Buchenholz',3,'Raummeter/Jahr',0,30,'Deine Angabe; keine Schüttraummeter'],['woodHeat','Heizwert je Raummeter Buche',1885,'kWh/Rm',1000,2500,'Schätzung bei ca. 20 % Wassergehalt; FNR'],['gasEfficiency','Nutzungsgrad Gasheizung',92.5,'%',50,100,'Modellannahme, nicht gemessen'],['stoveEfficiency','Nutzungsgrad Kaminofen',70,'%',20,90,'Modellannahme, nicht gemessen'],['weather','Wetterkorrektur für Wärmeverbrauch',1,'Faktor',0.7,1.4,'Unbekannt: Start 1,0 ohne Korrektur']]},
  {title:'Nach der Sanierung',intro:'Die Fußbodenheizung bietet gute Voraussetzungen. Die Jahresarbeitszahl umfasst Heizung und Warmwasser. Änderungen hier wirken nach Klick auf „Aus Hausdaten abgeleiteten WP-Verbrauch übernehmen“ auf die zentrale Simulation. PV-Deckung ist ein Jahresplanwert, keine Stundenberechnung.',fields:[
   ['jaz','Jahresarbeitszahl Wärmepumpe',3.75,'Wärme / Strom',1.5,6,'Geschätzte Mitte von 3,5–4,0'],['woodFuture','Holzverbrauch nach Sanierung',3,'Raummeter/Jahr',0,30,'Annahme: bisherige Nutzung bleibt'],['pvHeatShare','PV-Anteil am Wärmepumpenstrom',30,'%',0,70,'Vorsichtiger Planwert; saisonal ungeprüft']]},
  {title:'Lage & Zustand',intro:'Diese Antworten machen Unsicherheiten sichtbar. Sie erzeugen keine erfundenen Preisaufschläge. Quantifiziere Unterschiede erst mit lokalen Vergleichsobjekten oder einer Bewertung.',fields:[
   ['condition','Gebäudezustand','sehrgut',['sehrgut','gut','mittel','sanierung'],'Deine Angabe: sehr gut, laufend gepflegt'],['noise','Lärm / Mikrolage','unbekannt',['unbekannt','ruhig','mittel','belastet'],'Noch offen: Straße, Flugverkehr, Gewerbe'],['risk','Hochwasser / sonstige Belastungen','unbekannt',['unbekannt','geprüft ohne Befund','Belastung vorhanden'],'Noch offen: Gefahrenkarten, Altlasten, Rechte'],['landUse','Nutzbarkeit des großen Grundstücks','unbekannt',['unbekannt','Garten ohne weiteres Baurecht','zusätzliches Baurecht bestätigt'],'Noch offen: Baurecht und Grundstücksqualität'],['defects','Absehbare Reparaturen',0,'€',0,500000,'Vorläufig 0 €; bitte prüfen'],['brw','Bodenrichtwert (nur Plausibilitätsvergleich)',0,'€/m²',0,5000,'Unbekannt: 0 bedeutet nicht hinterlegt']]},
  {title:'Wert eingrenzen',intro:'Start: Mannheimer EFH-Durchschnitt aus Verkäufen 2025, 3.732 €/m². Er enthält Grundstücksanteile und ist für euer Objekt nur ein grober Anker. Der Bodenwert wird deshalb nicht zusätzlich addiert.',fields:[
   ['price','Vergleichspreis bestehender Häuser inkl. Grundstück',3732,'€/m² Wohnfläche',500,15000,'Mannheim 2025; noch kein Scharhof-Vergleich'],['localEvidence','Grundlage des Vergleichspreises','Stadtmittel',['Stadtmittel','lokale Angebote','vergleichbare Verkäufe / Bewertung'],'Bitte erst mit passenden Daten ändern'],['adjustment','Begründete Anpassung gegenüber Vergleich',0,'%',-50,50,'Start 0 %; Zustand, Größe, Garten und Vermietung gemeinsam prüfen'],['uncertainty','Bandbreite um den Rechenwert',30,'± %',5,60,'Vorsichtige Modellannahme; kein statistisches Konfidenzintervall'],['manualValue','Alternativer aktueller Gesamtwert',0,'€',0,20000000,'Optional: 0 nutzt Vergleichspreis × Wohnfläche'],['upliftLow','Wertzuwachs vorsichtig',3,'%',0,20,'Planannahme aus unserer Einschätzung'],['upliftBase','Wertzuwachs Basis',5,'%',0,20,'Planannahme; kein lokaler Marktnachweis'],['upliftHigh','Wertzuwachs optimistisch',7,'%',0,25,'Planannahme; kein garantierter Verkaufserlös']]}
 ];
 const fields=groups.flatMap(g=>g.fields),initial=Object.fromEntries(fields.map(f=>[f[0],f[2]]));
 let state={...initial},answered={},step=0;
 const fmt=(v,n=0)=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:n}).format(v), euro=v=>fmt(v)+' €';
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function normalize(raw){const s={...initial};if(!raw||typeof raw!=='object')return s;fields.forEach(f=>{const v=raw[f[0]];if(Array.isArray(f[3])){if(f[3].includes(v))s[f[0]]=v;}else if(typeof v==='number'&&Number.isFinite(v))s[f[0]]=Math.min(f[5],Math.max(f[4],v));});return s;}
 try{const data=JSON.parse(localStorage.getItem(KEY));if(data){state=normalize(data.state);answered=data.answered&&typeof data.answered==='object'?data.answered:{};}}catch(_){}
 function save(){try{localStorage.setItem(KEY,JSON.stringify({state,answered}));}catch(_){document.getElementById('houseStatus').textContent='Speicherung nicht verfügbar. Bitte JSON exportieren.';}}
 function calculate(s,projectWp){
  const wood=s.wood*s.woodHeat,gas=s.gas*0.9,thermal=gas*s.gasEfficiency/100+wood*s.stoveEfficiency/100;
  const futureWood=s.woodFuture*s.woodHeat,wp=Number.isFinite(projectWp)?projectWp:Math.max(0,thermal-futureWood*s.stoveEfficiency/100)/s.jaz;
  const today=(gas+wood)*s.weather/s.an,after=(wp+futureWood)*s.weather/s.an,grid=wp*(1-s.pvHeatShare/100);
  const area=s.ownArea+s.rentArea,anchor=area*s.price*(1+s.adjustment/100),base=Math.max(0,(s.manualValue>0?s.manualValue:anchor)-s.defects);
  const low=base*(1-s.uncertainty/100),high=base*(1+s.uncertainty/100);
  return {wood,gas,thermal,wp,today,after,grid,area,base,low,high,reduction:today?(1-after/today)*100:0};
 }
 function grade(v){return v<30?'A+':v<50?'A':v<75?'B':v<100?'C':v<130?'D':v<160?'E':v<200?'F':v<250?'G':'H';}
 function controls(){const g=groups[step];document.getElementById('houseQuestions').innerHTML=`<span class="eyebrow">SCHRITT ${step+1} / ${groups.length}</span><h2>${g.title}</h2><p>${g.intro}</p><div class="house-fields">`+g.fields.map(f=>{
  const [key,label,,unit]=f,source=Array.isArray(unit)?f[4]:f[6];
  return `<label for="house-${key}">${label}<span class="source-tag">${answered[key]?'Von dir angepasst':esc(source)}</span></label>`+(Array.isArray(unit)?`<select id="house-${key}" data-house="${key}">${unit.map(o=>`<option ${state[key]===o?'selected':''}>${esc(o)}</option>`).join('')}</select>`:`<div><input id="house-${key}" data-house="${key}" type="number" min="${f[4]}" max="${f[5]}" step="any" value="${state[key]}" required><small>${unit}</small></div>`);
 }).join('')+'</div>';
 document.getElementById('houseSteps').innerHTML=groups.map((g,i)=>`<button class="button ${i===step?'':'secondary'}" data-step="${i}" aria-current="${i===step?'step':'false'}">${i+1}. ${g.title}</button>`).join('');
 document.getElementById('housePrev').disabled=step===0;document.getElementById('houseNext').disabled=step===groups.length-1;
 }
 function bars(id,rows,unit){const max=Math.max(1,...rows.map(r=>r[1]));document.getElementById(id).innerHTML=rows.map(([label,v,color])=>`<div class="house-bar"><span>${label}</span><b>${fmt(v)} ${unit}</b><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%;background:${color}"></div></div></div>`).join('');}
 function render(){const active=window.energyActiveConfig?.(); const r=calculate(state,active?.wpDemand),s=state;
  document.getElementById('houseKpis').innerHTML=[['Heutiger Energiekennwert',fmt(r.today,1)+' kWh/m²','Verbrauchsnäherung · '+grade(r.today)+' · ohne gesicherte Wetterkorrektur'],['Nach Wärmepumpe',fmt(r.after,1)+' kWh/m²','Näherung · '+grade(r.after)+' · PV hier noch nicht abgezogen'],['Aktueller Wertkorridor',euro(Math.round(r.low/1000)*1000)+' – '+euro(Math.round(r.high/1000)*1000),'Grober Modellkorridor · keine Verkehrswertermittlung'],['Wertzuwachs Basis',euro(Math.round(r.base*s.upliftBase/100/1000)*1000),fmt(s.upliftBase,1)+' % Planannahme auf den Rechenwert']].map(([label,v,note])=>`<article class="hero-card"><span class="label">${label}</span><strong>${v}</strong><small>${note}</small></article>`).join('');
  bars('houseEnergyBars',[['Heute: Gas + Holz',r.gas+r.wood,'#f0bc76'],['Wärmepumpe: Strom + Holz',r.wp+s.woodFuture*s.woodHeat,'#88ecc2'],['WP-Strom aus dem Netz',r.grid,'#8cc7ef']],'kWh/Jahr');
  document.getElementById('houseEnergyDetail').textContent=`Aktives Modell: ${window.EnergyOfferProfiles?.[active?.offerId]?.name||'Eigene Werte'}; geplanter WP-Strom aus der zentralen Simulation. Historischer Gasverbrauch bleibt die bestätigte Hausangabe. Nutzwärme ca. ${fmt(r.thermal)} kWh/Jahr. Wärmepumpenstrom ca. ${fmt(r.wp)} kWh/Jahr, davon PV ${fmt(r.wp-r.grid)} kWh. Endenergie ohne PV-Anrechnung sinkt um ${fmt(r.reduction)} %. Eine Jahresbilanz ersetzt keinen neuen Energiebedarfsausweis. Aₙ ${fmt(s.an,2)} m²; Wohnfläche ${fmt(r.area)} m². Haushalts- und Wallboxstrom gehören nicht in diese Heizenergiekennzahl.`;
  const cases=[['Vorsichtig',s.upliftLow],['Basis',s.upliftBase],['Optimistisch',s.upliftHigh]];
  bars('houseValueBars',cases.map(([label,p])=>[label+' · '+fmt(p,1)+' %',r.base*(1+p/100),'#88ecc2']),'€');
  document.getElementById('houseValueTable').innerHTML=cases.map(([label,p])=>`<tr><th scope="row">${label}</th><td>${euro(r.base*p/100)}</td><td>${euro(r.low*(1+p/100))} – ${euro(r.high*(1+p/100))}</td></tr>`).join('');
  document.getElementById('houseValuationDetail').textContent=`${s.manualValue>0?'Alternativer Gesamtwert '+euro(s.manualValue):fmt(r.area)+' m² × '+euro(s.price)+'/m² × '+fmt(1+s.adjustment/100,2)} minus ${euro(s.defects)} Reparaturen = ${euro(r.base)} Rechenwert. Grundstück und Mietwohnung sind darin enthalten. Die Kaltmiete von ${euro(s.rent*12)} pro Jahr wird nicht als zusätzlicher Immobilienwert addiert. Bodenrichtwert-Plausibilität: ${s.brw>0?euro(s.brw*s.land)+' für '+fmt(s.land)+' m² (keine automatische Baulandbewertung)':'noch offen'}.`;
  const open=[];if(s.localEvidence==='Stadtmittel')open.push('Passende lokale Vergleichspreise fehlen.');if(!s.brw)open.push('Bodenrichtwert und wertrelevante Grundstücksfläche prüfen.');if(s.noise==='unbekannt')open.push('Lärmbelastung der Mikrolage klären.');if(s.risk==='unbekannt')open.push('Hochwasser, Altlasten und Grundstücksrechte prüfen.');if(s.landUse==='unbekannt')open.push('Nutzbarkeit und zusätzliches Baurecht des Grundstücks klären.');open.push('Dämmung vor Ort prüfen: Nachweis nennt teils 14 cm, deine Angabe 12 cm; Anlagenplanung enthält nicht vorhandene Solarthermie/Lüftung.');
  document.getElementById('houseOpen').innerHTML=open.map(t=>'<li>'+esc(t)+'</li>').join('');
  document.getElementById('houseAnswered').textContent=`${Object.keys(answered).filter(k=>answered[k]&&Object.hasOwn(initial,k)).length} von ${fields.length} Werten von dir angepasst. Dies misst Bearbeitung, nicht Bewertungsgenauigkeit.`;
 }
 function exportData(){return {version:2,house:state,edited:answered,assumptions:{gasHeatingValueFactor:0.9,valuation:'Vergleichspreis inklusive Grundstück; keine kalibrierte Verkehrswertermittlung',energy:'Verbrauchsnäherung, kein Energieausweis'},sources:['Gasabrechnung 2025','Wärmeschutznachweis 2006','Angaben Eigentümer','Mannheimer Grundstücksmarkt 2025','immowelt 2026']};}
 window.energyHouseExport=exportData;
 window.energyHouseModel={calculate,normalize,defaults:()=>({...initial})};
 function init(){const root=document.getElementById('propertyApp');root.innerHTML=`
  <div class="section-intro"><div><span class="eyebrow">MANNHEIM · SCHARHOF</span><h2>Dein Haus. Heute und morgen.</h2><p>Bekannte Daten prüfen, offene Fragen beantworten und Energie- und Wertspannen erkunden.</p></div></div>
  <div id="houseKpis" class="hero-grid house-kpis"></div>
  <div class="two-col"><article class="card"><h2>Dein Hausprofil</h2><p>Einfamilienhaus mit vermieteter Einliegerwohnung. Gehobene Ausstattung, Parkett, Fußbodenheizung, Terrasse, großer Garten mit unbeheiztem Pool. Kein Keller. Holzfenster aus der Bauzeit, frisch gestrichen. Dach gedämmt; Fensterlüftung. Gasheizung Vitodens 200, zentrales Warmwasser, Raumtemperatur 21 °C. Keine Solarthermie und keine Lüftungsanlage.</p><span class="pill">Angaben von dir</span><p>Wärmeschutznachweis: Dach U ≈ 0,21, Fenster U ≈ 1,30, Bodenplatte U ≈ 0,18 W/(m²K). Planungswerte, kein Nachweis der heutigen Ausführung. Der damalige Energiebedarf wird wegen abweichender Anlagentechnik nicht übernommen.</p></article><article class="card"><h2>Was braucht noch eine Antwort?</h2><ul id="houseOpen"></ul><p id="houseAnswered"></p></article></div>
  <article class="card"><div id="houseSteps" class="house-steps" aria-label="Frageschritte"></div><div id="houseQuestions"></div><div class="house-actions"><button id="housePrev" class="button secondary">← Zurück</button><button id="houseNext" class="button">Weiter →</button></div><p id="houseStatus" role="status" aria-live="polite"></p></article>
  <div class="two-col"><article class="card"><h2>Energie vor und nach Sanierung</h2><div id="houseEnergyBars"></div><p id="houseEnergyDetail"></p><button id="houseSync" class="button secondary">Aus Hausdaten abgeleiteten WP-Verbrauch übernehmen</button><p>Bewusste Übernahme: ersetzt die dortigen Verbrauchswerte und wechselt zu Manuell. PV-Deckung dieser Seite bleibt eine eigenständige Heizenergieannahme.</p></article><article class="card"><h2>Wert nach PV + Wärmepumpe</h2><div id="houseValueBars"></div><div class="table-wrap"><table><thead><tr><th>Szenario</th><th>Mehrwert auf Rechenwert</th><th>Gesamtwert nach Sanierung</th></tr></thead><tbody id="houseValueTable"></tbody></table></div><p id="houseValuationDetail"></p><p>Wertzuwachs wird separat gezeigt und nicht dem Energie-Cashflow zugeschlagen. PV, Wärmepumpe und mögliche Speicher werden nicht mit einzelnen Aufschlägen doppelt gezählt.</p></article></div>
  <article class="card"><h2>Grundlagen & Grenzen</h2><p>3 / 5 / 7 % sind unsere Planannahmen für ein bereits gut gedämmtes Haus. Die immowelt-Auswertung 2026 zeigt bundesweite Angebotspreisunterschiede gegenüber D: C +1 %, B +4 %, A +7 %, A+ +15 %. Diese sind keine garantierten Sanierungsgewinne und werden nicht automatisch auf euer Haus übertragen. Mikrolage, Baurecht, Vermietung und außergewöhnliche Grundstücksgröße können die lokale Bewertung stark verändern.</p><p>Eine bessere Energieklasse verändert die Gebäudehülle nicht. Eine Wärmepumpe reduziert den Energieeinsatz; PV deckt einen Teil des Strombedarfs. Normgerechte PV-Anrechnung und bestätigte Energieklasse benötigen eine neue Berechnung. Technischer Hilfsstrom und wetterbereinigte Mehrjahresverbräuche fehlen hier.</p><div class="house-sources"><a target="_blank" rel="noopener" href="https://www.mannheim.de/de/presse/preise-auf-dem-immobilienmarkt-in-teilen-leicht-steigend-grundstuecksmarktbericht-2025-des">Mannheim: Verkäufe 2025</a><a target="_blank" rel="noopener" href="https://www.mannheim.de/de/stadt-gestalten/planungskonzepte/bodenrichtwerte">Bodenrichtwert suchen</a><a target="_blank" rel="noopener" href="https://content.cdn.immowelt.com/iw_group2/import/Redaktion/Pressemitteilungen/2026/2026_03_19_PM_Energieeffizienz_Preiseinfluss_final.pdf">immowelt: Energie & Angebotspreise</a><a target="_blank" rel="noopener" href="https://www.gebaeudeforum.de/service/faq/">dena: Energieausweis</a><a target="_blank" rel="noopener" href="https://heizen.fnr.de/heizen-mit-holz/der-brennstoff-holz">FNR: Holzheizwert</a></div><p>Nur lokale Speicherung. Beim Veröffentlichen sind diese vorausgefüllten Haus- und Mietdaten öffentlich. Die Original-PDFs und persönlichen Abrechnungsdaten werden nicht mitgeliefert.</p><button id="houseReset" class="button secondary">Hausdaten auf Startwerte setzen</button></article>`;
  controls();render();
  window.addEventListener('energy-config-change',render);
  root.addEventListener('input',e=>{const key=e.target.dataset.house;if(!key)return;const f=fields.find(f=>f[0]===key);if(!Array.isArray(f[3])&&!e.target.checkValidity()){e.target.reportValidity();document.getElementById('houseStatus').textContent='Bitte einen Wert im angezeigten Bereich eingeben. Das Ergebnis nutzt weiterhin den letzten gültigen Wert.';return;}state[key]=Array.isArray(f[3])?e.target.value:Number(e.target.value);state=normalize(state);answered[key]=true;document.getElementById('houseStatus').textContent='Wert übernommen. Ergebnisse aktualisiert.';render();save();});
  root.addEventListener('click',e=>{const button=e.target.closest('[data-step]');if(button){step=Number(button.dataset.step);controls();}});
  document.getElementById('housePrev').onclick=()=>{step=Math.max(0,step-1);controls();};document.getElementById('houseNext').onclick=()=>{step=Math.min(groups.length-1,step+1);controls();};
  document.getElementById('houseReset').onclick=()=>{state={...initial};answered={};step=0;controls();render();save();};
  document.getElementById('houseSync').onclick=()=>{const r=calculate(state);[['gasDemand',state.gas],['wpDemand',r.wp]].forEach(([key,value])=>{const input=document.getElementById('param-'+key);input.value=Math.round(value);input.dispatchEvent(new Event('input',{bubbles:true}));});document.getElementById('houseStatus').textContent='Gas- und Wärmepumpenverbrauch wurden in die Wirtschaftlichkeit übernommen.';};
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();


